"""Add finalizada flag to compra

Revision ID: 1832096e55a4
Revises: 9206d78e34c3
Create Date: 2025-10-29 23:12:51.178445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1832096e55a4'
down_revision = '9206d78e34c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finalizada', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compra', schema=None) as batch_op:
        batch_op.drop_column('finalizada')

    # ### end Alembic commands ###
