"""Migração inicial - Criação de todas as tabelas

Revision ID: 9206d78e34c3
Revises: 
Create Date: 2025-10-28 22:31:21.236577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9206d78e34c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_barras', sa.String(length=100), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_barras')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('hash_senha', sa.String(length=128), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_compra', sa.DateTime(), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lista_de_compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_da_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preco_pago', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['compra_id'], ['compra.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_da_lista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao_item', sa.String(length=300), nullable=False),
    sa.Column('concluido', sa.Boolean(), nullable=True),
    sa.Column('lista_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lista_id'], ['lista_de_compras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_da_lista')
    op.drop_table('item_da_compra')
    op.drop_table('lista_de_compras')
    op.drop_table('compra')
    op.drop_table('usuario')
    op.drop_table('produto')
    # ### end Alembic commands ###
